### ISSUE TITLE
debug does not work

### ISSUE THREAD

**Issue by sobolevn** [clarkdo/hare#332]
Thanks for the detailed example!

When trying to launch `vscode` with `Hare Dev` it just opens regular `nuxt` app.
Breakpoints do not work. `debugger` does not work to. They are just ignored. 

![2018-05-10 0 35 19](https://user-images.githubusercontent.com/4660275/39841043-316a6f68-53ea-11e8-8a4a-502acc0c1333.png)

When trying to launch `Hare Prod` it fails with this exception:
![2018-05-10 0 35 36](https://user-images.githubusercontent.com/4660275/39841083-4e4f6340-53ea-11e8-8908-6a0e646eb9a6.png)

I am using:
- `node@9.10`
- `vscode` with version `1.23.0 7c7da59c2333a1306c41e6e7b68d7f0caa7b3d45 x64`
- `yarn@1.6`

Thanks!

<div align="right"><sub><em>This question is available on <a href="https://nuxtjs.cmty.io">Nuxt.js</a> community (<a href="https://nuxtjs.cmty.io/clarkdo/hare/issues/c6">#c6</a>)</em></sub></div>

**Comment by clarkdo** [comment]
Could you have a try on latest `dev` branch ?

**Comment by sobolevn** [comment]
@clarkdo now it is working, but there is an unsolved `sourcemap` problem.
![2018-05-23 13 15 29](https://user-images.githubusercontent.com/4660275/40418583-70a9dc6c-5e8b-11e8-859f-919776ac3e38.png)

Orignal issue: https://github.com/nuxt/nuxt.js/issues/2734

**Comment by clarkdo** [comment]
@sobolevn Thank you for the confirmation, so I gonna close this issue and keep tracing the issue you mentioned.
