### ISSUE TITLE
'debug' should be an explicit dependency

### ISSUE THREAD

**Issue by pearofducks** [clarkdo/hare#333]
It seems (unless I've not looked in the right place) that _debug_ is [being used](https://github.com/clarkdo/hare/blob/dev/server/app.js#L16), but it isn't specified in the package dependencies.

It likely still works since several dependencies list it as a sub-dependency, but this means its version can't be controlled for.

<div align="right"><sub><em>This question is available on <a href="https://nuxtjs.cmty.io">Nuxt.js</a> community (<a href="https://nuxtjs.cmty.io/clarkdo/hare/issues/c9">#c9</a>)</em></sub></div>

**Comment by clarkdo** [comment]
@pearofducks Thanks for the notice, I have removed `debug` in https://github.com/clarkdo/hare/commit/ac070a12ca809bd2546e58bebe3a6bdd1e083800 since it's not very necessary.
