### ISSUE TITLE
Add github issue template

### ISSUE THREAD

**Issue by sobolevn** [clarkdo/hare#337]
### What problem does this feature solve?

When creating my first issue for this project I was not informed on how to do it properly. 
Since there's no clean sign about using `cmty.io`.

So, for future contributors it would be very nice to add a template that states, that issues must be created on `cmty.io`.
Or they will be closed otherwise.

<div align="right"><sub><em>This feature request is available on <a href="https://nuxtjs.cmty.io">Nuxt.js</a> community (<a href="https://nuxtjs.cmty.io/clarkdo/hare/issues/c11">#c11</a>)</em></sub></div>

**Comment by sobolevn** [comment]
Wrong repo, sorry. `cmty` is a kind of mess 🙂

**Comment by sobolevn** [comment]
Actually, this issue applies to this repo as well.

**Comment by clarkdo** [comment]
@sobolevn Thanks. Issue template has been added in https://github.com/clarkdo/hare/commit/bd1fc78bd520da2e5955ba4357b3ecec8f3c5976
