### ISSUE TITLE
麻烦问一下国际化那边切换语言的入口在哪

### ISSUE THREAD

**Issue by bluescurry** [clarkdo/hare#338]
<div align="right"><sub><em>This question is available on <a href="https://nuxtjs.cmty.io">Nuxt.js</a> community (<a href="https://nuxtjs.cmty.io/clarkdo/hare/issues/c17">#c17</a>)</em></sub></div>

**Comment by clarkdo** [comment]
抱歉， 因为没有按照issue_template提issue， 导致被机器人自动关闭。

文件在： https://github.com/clarkdo/hare/tree/dev/client/locales
