### ISSUE TITLE
process.env available in generate: route function

### ISSUE THREAD

**Issue by dsmurl** [clarkdo/hare#340]
### What problem does this feature solve?

there is no access to the process.env inside the functions inside generate::route.  This means that one must commit secrets to the github repo if they are needed to make a call during the generation of static pages.  Not a real world example below but is relavant to my situation.

Like:  
```
generate: {
    routes: function() {
      const secretURL = process.env.API_URL + '?API_KEY=' + process.env.API_KEY;   // process =.env here won't work here like in the 

      return axios.get(secretURL)
        .then(res => { 
```

### What does the proposed changes look like?

```
  generate: {
    routes: function(contect or env) {
```

or just have generate run route functions somewhere where process.env is visible to the functions.

<div align="right"><sub><em>This feature request is available on <a href="https://nuxtjs.cmty.io">Nuxt.js</a> community (<a href="https://nuxtjs.cmty.io/clarkdo/hare/issues/c22">#c22</a>)</em></sub></div>

**Comment by clarkdo** [comment]
@dsmurl I think you opened the issue to the wrong repo 😄
