### ISSUE TITLE
How about multi language in the sitemap configuration

### ISSUE THREAD

**Issue by OlegLevitskiy** [clarkdo/hare#343]
### What problem does this feature solve?

I'm working with a multilingual project, and i using the @nuxt/sitemap module. Could you help me show how to customize this module for multi language?

<div align="right"><sub><em>This feature request is available on <a href="https://cmty.app/nuxt">Nuxt</a> community (<a href="https://cmty.app/nuxt/hare/issues/c43">#c43</a>)</em></sub></div>

**Comment by clarkdo** [comment]
@OlegLevitskiy Do you mean you want to integrate @nuxt/sitemap into Hare? I'm just a little confused maybe you opened issue at wrong repo.
