### ISSUE TITLE
Head components

### ISSUE THREAD

**Issue by galvez** [clarkdo/hare#344]
### What problem does this feature solve?

Just for better code organization, it would be nice to be able to define <head> as a Vue component in nuxt.config.js, similarly to what is done with `loading`.

### What does the proposed changes look like?

Just something like:

```js
head: '~/components/Head'
```

<div align="right"><sub><em>This feature request is available on <a href="https://cmty.app/nuxt">Nuxt</a> community (<a href="https://cmty.app/nuxt/hare/issues/c45">#c45</a>)</em></sub></div>

**Comment by clarkdo** [comment]
@galvez Regarding to this request, you can open a ticket in nuxtjs repo
