### ISSUE TITLE
Nuxt-link-active is added as a class multiple times, even when it shouldn't really be

### ISSUE THREAD

**Issue by kgrosvenor** [clarkdo/hare#345]
### Version

[v0.4.0](https://github.com/hare/releases/tag/v0.4.0)

### Reproduction link

[http://178.128.44.34](http://178.128.44.34)

### Steps to reproduce

Go to workshops > traditional barbering and inspect element on the navigation section.

### What is expected ?

Only that workshops tab  is active

### What is actually happening?

Its setting active on / when in a child view /workshops 

### Additional comments?

Any idea why this is? 
My project structure follows just like in docs

<div align="right"><sub><em>This bug report is available on <a href="https://cmty.app/nuxt">Nuxt</a> community (<a href="https://cmty.app/nuxt/hare/issues/c52">#c52</a>)</em></sub></div>

**Comment by clarkdo** [comment]
@kgrosvenor The issue seemed being opened in wrong repo.
