### ISSUE TITLE
[edge] [nuxt] Error while initializing app DOMException

### ISSUE THREAD

**Issue by nallown** [clarkdo/hare#347]
### Version

[2](https://github.com/hare/releases/tag/2)

### Reproduction link

[https://test.twist.moe/a/07-ghost/1](https://test.twist.moe/a/07-ghost/1)

### Steps to reproduce

1. Go to the reproduction link
2. Login with username: `public` and password: `not`
3. Check Dev-Tools console

### What is expected ?

The website should render fine and it should play the video.

### What is actually happening?

It throws an error in the console.

### Additional comments?

I tried to upgrade my nuxt version to 2.0 and I get the following error:
```
[nuxt] Error while initializing app DOMException: Failed to execute 'appendChild' on 'Node': This node type does not support this method.
```

I've updated the Nuxt version to nuxt-edge and I also updated other node modules version to work with nuxt-edge and webpack 4. I freshly installed the node_modules so I removed the folder and ran a fresh `npm i`. When I run the dev version of the build, it works fine. It only fails with the production build. All the unit test pass just like they did before I only started getting this error after the nuxt-edge and webpack 4 upgrade. The website works fine and everything builds without a error, there were no issues until I upgraded my project to nuxt-edge and started the nuxt server in production.

I can give you access to the repository the project is very easy to setup, the dev version of the project works without internet, it uses mock network requests for the API. Just ask and I can give you access. 

<div align="right"><sub><em>This bug report is available on <a href="https://cmty.app/nuxt">Nuxt</a> community (<a href="https://cmty.app/nuxt/hare/issues/c61">#c61</a>)</em></sub></div>

**Comment by clarkdo** [comment]
Issue should be submitted to Nuxt.js 😄

**Comment by nallown** [comment]
oh wow lol, how did this end up here I thought I submitted it to Nuxt.js

**Comment by nallown** [comment]
Moved to: https://github.com/nuxt/nuxt.js/issues/3575
