### ISSUE TITLE
Can no longer stage & push create-nuxt-app create projects that are new

### ISSUE THREAD

**Issue by amandablakley** [clarkdo/hare#348]
### Version

[v0.4.0](https://github.com/hare/releases/tag/v0.4.0)

### Reproduction link

[https://github.com/nuxt-community/create-nuxt-app](https://github.com/nuxt-community/create-nuxt-app)

### Steps to reproduce

Create nuxt project through terminal with npx create-nuxt-app <my-project> and follow steps.

### What is expected ?

When you stage project you should be able to stage and push to github repo.

### What is actually happening?

You can not stage project at all, let alone push. Gitkraken and source tree both throw errors stating they can not find master head. There were no issues with this repo prior to the last commit in the last 20 hours.

<div align="right"><sub><em>This bug report is available on <a href="https://cmty.app/nuxt">Nuxt</a> community (<a href="https://cmty.app/nuxt/hare/issues/c64">#c64</a>)</em></sub></div>

**Comment by clarkdo** [comment]
@amandablakley The issue seemed being opened in wrong repo.
