### ISSUE TITLE
baseURL does not take effect

### ISSUE THREAD

**Issue by begueradj** [clarkdo/hare#356]
### Version

[v0.4.0](https://github.com/hare/releases/tag/v0.4.0)

### Reproduction link

[https://github.com/begueradj/nuxt-axios-baseurl-bug](https://github.com/begueradj/nuxt-axios-baseurl-bug)

### Steps to reproduce

1. Clone my repo and change to the resulted directory 
2. Intall the dependencites: `yarn install`
3. Launch the server: `yarn run dev`

### What is expected ?

I expect the number of displayed posts to be 100.

This means in `pages/index.vue`, when I have this code:

```
mounted() {
    axios.get('/posts')
    .then(response => {
      this.posts = response.data
    })
    .catch(e => {
      this.errors.push(e)
    })
  }
```

axios should recoginize the `baseURL` configuration key I set in `nuxt.config.js` and thus fetch data from http://jsonplaceholder.typicode.com/posts

Here is my `nuxt.config.js` file content related to axios module:

```
modules: [
    // Doc: https://github.com/nuxt-community/axios-module#usage
    ['@nuxtjs/axios', {
      baseURL: 'http://jsonplaceholder.typicode.com'
    }]
  ],
  /*
  ** Axios module configuration
  */
  axios: {
    // See https://github.com/nuxt-community/axios-module#options
  },
```

### What is actually happening?

The number of displayed posts is 0
axios is trying to send a get request to  http://localhost/posts instead of http://jsonplaceholder.typicode.com/posts

### Additional comments?

I checked similar posts but nothing worked for me.

Thanks,
Billal Begueradj

<div align="right"><sub><em>This bug report is available on <a href="https://cmty.app/nuxt">Nuxt</a> community (<a href="https://cmty.app/nuxt/hare/issues/c109">#c109</a>)</em></sub></div>

**Comment by clarkdo** [comment]
@begueradj The issue seemed being opened in wrong repo.
