### ISSUE TITLE
import of type for JSONValue missing

### ISSUE THREAD

**Issue by Lisiadito** [clarkdo/hare#412]
### Version

[v0.1.1](https://github.com/hare/releases/tag/v0.1.1)

### Reproduction link

[https://github.com/nuxt/http/blob/dev/types/index.d.ts](https://github.com/nuxt/http/blob/dev/types/index.d.ts)

### Steps to reproduce

Using the @nuxt/http module with TypeScript leads to an error `Cannot find name 'JSONValue'`

### What is expected ?

Compilation works without problems

### What is actually happening?

Error `Cannot find name 'JSONValue'` because the type is used but not imported

<div align="right"><sub><em>This bug report is available on <a href="https://cmty.app/nuxt">Nuxt</a> community (<a href="https://cmty.app/nuxt/hare/issues/c123">#c123</a>)</em></sub></div>

**Comment by Lisiadito** [comment]
sorry wrong repository. can be closed.

**Comment by renoirb** [comment]
No problem :)
